
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 22 17:55:40 CDT 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 7;
  public static final int Parentesis_c = 15;
  public static final int Char = 5;
  public static final int Parentesis_a = 14;
  public static final int Suma = 10;
  public static final int Numero = 21;
  public static final int ERROR = 22;
  public static final int Identificador = 20;
  public static final int Comillas = 3;
  public static final int Int = 4;
  public static final int Llave_c = 17;
  public static final int Llave_a = 16;
  public static final int P_coma = 19;
  public static final int Main = 18;
  public static final int EOF = 0;
  public static final int Division = 13;
  public static final int Resta = 11;
  public static final int If = 6;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int Igual = 9;
  public static final int While = 8;
  public static final int Multiplicacion = 12;
}

