
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 22 18:53:54 CDT 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 8;
  public static final int Parentesis_c = 16;
  public static final int Char = 6;
  public static final int Parentesis_a = 15;
  public static final int Suma = 11;
  public static final int Numero = 23;
  public static final int ERROR = 24;
  public static final int Identificador = 22;
  public static final int Comillas = 3;
  public static final int Int = 5;
  public static final int Llave_c = 18;
  public static final int Llave_a = 17;
  public static final int P_coma = 21;
  public static final int Main = 19;
  public static final int EOF = 0;
  public static final int Division = 14;
  public static final int Comilla = 4;
  public static final int Resta = 12;
  public static final int If = 7;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int Void = 20;
  public static final int Igual = 10;
  public static final int While = 9;
  public static final int Multiplicacion = 13;
}

