
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 24 18:20:11 CDT 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 10;
  public static final int Parentesis_c = 18;
  public static final int Parentesis_a = 17;
  public static final int Char = 6;
  public static final int Suma = 13;
  public static final int Numero = 25;
  public static final int Float = 7;
  public static final int ERROR = 26;
  public static final int Identificador = 24;
  public static final int Comillas = 3;
  public static final int Int = 5;
  public static final int Llave_c = 20;
  public static final int Llave_a = 19;
  public static final int P_coma = 23;
  public static final int Main = 21;
  public static final int EOF = 0;
  public static final int Division = 16;
  public static final int Comilla = 4;
  public static final int Resta = 14;
  public static final int If = 9;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int Punto = 8;
  public static final int Void = 22;
  public static final int Igual = 12;
  public static final int While = 11;
  public static final int Multiplicacion = 15;
}

